### PR TITLE
Add new scam links, fix typos, update readme.md

### PR DESCRIPTION
**Pull request by InvalidLenni**
I add other links tomorrow (utc+1).

### CODE REVIEW

**Comment by 2Lost4This** [comment]
No worries

**Comment by InvalidLenni** [comment]
So, can you open it again?

**Comment by 2Lost4This** [comment]
> So, can you open it again?

🔓

**Comment by InvalidLenni** [comment]
thanks i would to change the readme.md

**Comment by 2Lost4This** [comment]
> thanks i would to change the readme.md

Changing what?

**Comment by InvalidLenni** [comment]
> > thanks i would to change the readme.md
> 
> Changing what?

I committed it

**Comment by 2Lost4This** [comment]
> > > thanks i would to change the readme.md
> > 
> > Changing what?
> 
> I committed it

So i can close this?

**Comment by InvalidLenni** [comment]
> > > > thanks i would to change the readme.md
> > > 
> > > 
> > > Changing what?
> > 
> > 
> > I committed it
> 
> So i can close this?

Nope, merge after the checks are done

**Pull request merged**
